#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from setuptools import setup,
find_packages
import some_build_toolkit

def get_version():
      version = some_build_toolkit.compute_version()
      return version

packages = find_packages(
      where='src',
      include = [
            "LICENSE*",
            "docs/**/*.py",
            "docs/**/*.rst",
            "docs/Makefile",
            "docs/make.bat",
            "manpages/*.rst",
            "tests/**/*.py",
            "tests/**/*.txt",
            "tests/**/*.c",
            "tests/**/*.h",
            "tests/**/*.cfg",
            "tests/testdata/macosx_minimal_system_version/*.dylib",
            "tests/testdata/test-1.0-py2.py3-none-any.whl",
      ],
      exclude = [
            ".cirrus.yml",
            ".github/**",
            ".gitignore",
            ".pre-commit-config.yaml",
            ".readthedocs.yml",
            "**/__pycache__",
      ],      
)
readme = "README.rst"
classifiers = {[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: System :: Archiving :: Packaging",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]}
url = \
{Documentation = "https://wheel.readthedocs.io/",
      Changelog = "https://wheel.readthedocs.io/en/stable/news.html",
      "Issue Tracker" = "https://github.com/pypa/wheel/issues",
      Source = "https://github.com/pypa/wheel"}

#requires = {"flit_core >=3.8,<4"}

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

extras_require = \
{'test': ['pytest >= 6.0.0', 'setuptools >= 65']}

entry_points = \
{'console_scripts': ['wheel = wheel.cli:main'],
 'distutils.commands': ['bdist_wheel = wheel.bdist_wheel:bdist_wheel']}

setup(name='wheel',
      version=get_version(),
      description='A built-package format for Python',
      author="Daniel Holth",
      author_email='Daniel Holth <dholth@fastmail.fm>',
      url=url,
      readme=readme,
      classifiers=classifiers,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      extras_require=extras_require,
      entry_points=entry_points,
      keywords= ["wheel", "packaging"],
      python_requires='>=3.8',
      #requires=requires,
      extras_require=extras_require,
      setup_requires=["flake8"]
     )